// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\Admin\go\src\url-shortener\internal\app\utility\base62.go

// Package utility is a generated GoMock package.
package utility

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIBase62Encoder is a mock of IBase62Encoder interface.
type MockIBase62Encoder struct {
	ctrl     *gomock.Controller
	recorder *MockIBase62EncoderMockRecorder
}

// MockIBase62EncoderMockRecorder is the mock recorder for MockIBase62Encoder.
type MockIBase62EncoderMockRecorder struct {
	mock *MockIBase62Encoder
}

// NewMockIBase62Encoder creates a new mock instance.
func NewMockIBase62Encoder(ctrl *gomock.Controller) *MockIBase62Encoder {
	mock := &MockIBase62Encoder{ctrl: ctrl}
	mock.recorder = &MockIBase62EncoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBase62Encoder) EXPECT() *MockIBase62EncoderMockRecorder {
	return m.recorder
}

// ConvertUniqueKeyToUrlPath mocks base method.
func (m *MockIBase62Encoder) ConvertUniqueKeyToUrlPath(uniqueKey uint64) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertUniqueKeyToUrlPath", uniqueKey)
	ret0, _ := ret[0].(string)
	return ret0
}

// ConvertUniqueKeyToUrlPath indicates an expected call of ConvertUniqueKeyToUrlPath.
func (mr *MockIBase62EncoderMockRecorder) ConvertUniqueKeyToUrlPath(uniqueKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertUniqueKeyToUrlPath", reflect.TypeOf((*MockIBase62Encoder)(nil).ConvertUniqueKeyToUrlPath), uniqueKey)
}
