// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\Admin\go\src\url-shortener\internal\app\utility\redis_key_generator.go

// Package utility is a generated GoMock package.
package utility

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIRedisKeyGenerator is a mock of IRedisKeyGenerator interface.
type MockIRedisKeyGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockIRedisKeyGeneratorMockRecorder
}

// MockIRedisKeyGeneratorMockRecorder is the mock recorder for MockIRedisKeyGenerator.
type MockIRedisKeyGeneratorMockRecorder struct {
	mock *MockIRedisKeyGenerator
}

// NewMockIRedisKeyGenerator creates a new mock instance.
func NewMockIRedisKeyGenerator(ctrl *gomock.Controller) *MockIRedisKeyGenerator {
	mock := &MockIRedisKeyGenerator{ctrl: ctrl}
	mock.recorder = &MockIRedisKeyGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRedisKeyGenerator) EXPECT() *MockIRedisKeyGeneratorMockRecorder {
	return m.recorder
}

// GenerateRedisKeyForUrl mocks base method.
func (m *MockIRedisKeyGenerator) GenerateRedisKeyForUrl(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRedisKeyForUrl", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateRedisKeyForUrl indicates an expected call of GenerateRedisKeyForUrl.
func (mr *MockIRedisKeyGeneratorMockRecorder) GenerateRedisKeyForUrl(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRedisKeyForUrl", reflect.TypeOf((*MockIRedisKeyGenerator)(nil).GenerateRedisKeyForUrl), arg0)
}
